package SAPSReads;

import java.awt.Color;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

public class MainUI extends javax.swing.JFrame {
    
    public MainUI() {
		//Initialize UI and its components
        initComponents();
		
		//Setting icon for the program from the imported project resource
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("open-book.png")));
		
		//Setting background color of the form pane
        getContentPane().setBackground(new Color(255, 255, 255));
    }
    
	//The list of all PatientInfo classes to store a collection of data
	//We are gonna use this array list as our database/data source for the program
    ArrayList<ClientInfo> clientDatabase = new ArrayList<>();
    ArrayList<BookInfo> bookDatabase = new ArrayList<>();
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        readersList = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        __ID = new javax.swing.JTextField();
        __name = new javax.swing.JTextField();
        __readerName = new javax.swing.JTextField();
        __issueDate = new javax.swing.JTextField();
        __dueDate = new javax.swing.JTextField();
        __phoneNumber = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        __email = new javax.swing.JTextField();
        issueBookBtn = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        returnBookBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        booksList = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        id__ = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        name__ = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        price__ = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        genere__ = new javax.swing.JTextField();
        addBookBtn = new javax.swing.JButton();
        removeBookBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SAPS Reads");
        setBackground(new java.awt.Color(20, 20, 20));
        setLocationByPlatform(true);
        setMaximizedBounds(new java.awt.Rectangle(890, 890, 890, 890));
        setMaximumSize(new java.awt.Dimension(890, 890));
        setPreferredSize(new java.awt.Dimension(890, 890));
        setResizable(false);
        setSize(new java.awt.Dimension(890, 890));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("SAPS Reads");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(50, 50, 50));
        jLabel2.setText("Success comes from knowledge");

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(70, 70, 70));
        jLabel3.setText("Issue/Retun book");

        readersList.setBackground(new java.awt.Color(255, 255, 255));
        readersList.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        readersList.setForeground(new java.awt.Color(51, 204, 0));
        readersList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(readersList);

        jPanel1.setBackground(new java.awt.Color(51, 255, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Book ID");

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Book Name");

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Reader Name");

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Issue Date");

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Phone no.");

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Due Date");

        __ID.setBackground(new java.awt.Color(255, 255, 255));
        __ID.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 10)); // NOI18N
        __ID.setForeground(new java.awt.Color(0, 0, 0));

        __name.setBackground(new java.awt.Color(255, 255, 255));
        __name.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 10)); // NOI18N
        __name.setForeground(new java.awt.Color(0, 0, 0));

        __readerName.setBackground(new java.awt.Color(255, 255, 255));
        __readerName.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 10)); // NOI18N
        __readerName.setForeground(new java.awt.Color(0, 0, 0));

        __issueDate.setBackground(new java.awt.Color(255, 255, 255));
        __issueDate.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 10)); // NOI18N
        __issueDate.setForeground(new java.awt.Color(0, 0, 0));

        __dueDate.setBackground(new java.awt.Color(255, 255, 255));
        __dueDate.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 10)); // NOI18N
        __dueDate.setForeground(new java.awt.Color(0, 0, 0));

        __phoneNumber.setBackground(new java.awt.Color(255, 255, 255));
        __phoneNumber.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 10)); // NOI18N
        __phoneNumber.setForeground(new java.awt.Color(0, 0, 0));

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Email");

        __email.setBackground(new java.awt.Color(255, 255, 255));
        __email.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 10)); // NOI18N
        __email.setForeground(new java.awt.Color(0, 0, 0));

        issueBookBtn.setBackground(new java.awt.Color(255, 255, 255));
        issueBookBtn.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        issueBookBtn.setForeground(new java.awt.Color(0, 204, 51));
        issueBookBtn.setText("Issue Book");
        issueBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBookBtnActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(70, 70, 70));
        jLabel34.setText("Add/remove new book");

        returnBookBtn.setBackground(new java.awt.Color(255, 255, 255));
        returnBookBtn.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        returnBookBtn.setForeground(new java.awt.Color(0, 204, 51));
        returnBookBtn.setText("Return book");
        returnBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookBtnActionPerformed(evt);
            }
        });

        booksList.setBackground(new java.awt.Color(255, 255, 255));
        booksList.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        booksList.setForeground(new java.awt.Color(51, 204, 0));
        booksList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(booksList);

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Book ID");

        id__.setBackground(new java.awt.Color(255, 255, 255));
        id__.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 10)); // NOI18N
        id__.setForeground(new java.awt.Color(0, 0, 0));

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Book Name");

        name__.setBackground(new java.awt.Color(255, 255, 255));
        name__.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 10)); // NOI18N
        name__.setForeground(new java.awt.Color(0, 0, 0));

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Book Price");

        price__.setBackground(new java.awt.Color(255, 255, 255));
        price__.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 10)); // NOI18N
        price__.setForeground(new java.awt.Color(0, 0, 0));

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Genere");

        genere__.setBackground(new java.awt.Color(255, 255, 255));
        genere__.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 10)); // NOI18N
        genere__.setForeground(new java.awt.Color(0, 0, 0));

        addBookBtn.setBackground(new java.awt.Color(255, 255, 255));
        addBookBtn.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        addBookBtn.setForeground(new java.awt.Color(0, 204, 51));
        addBookBtn.setText("Add book");
        addBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookBtnActionPerformed(evt);
            }
        });

        removeBookBtn.setBackground(new java.awt.Color(255, 255, 255));
        removeBookBtn.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        removeBookBtn.setForeground(new java.awt.Color(0, 204, 51));
        removeBookBtn.setText("Remove Book");
        removeBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBookBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                    .addComponent(returnBookBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(issueBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel6))
                                                .addGap(80, 80, 80)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(__issueDate, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                                                    .addComponent(__dueDate)
                                                    .addComponent(__phoneNumber)
                                                    .addComponent(__readerName)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel4))
                                                .addGap(89, 89, 89)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(__ID)
                                                    .addComponent(__name)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13)
                                        .addGap(127, 127, 127)
                                        .addComponent(__email)))))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(removeBookBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel10))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(id__)
                                            .addComponent(name__)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(price__, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                                            .addComponent(genere__))))
                                .addContainerGap())
                            .addComponent(addBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__readerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__issueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__dueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(issueBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(returnBookBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id__, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name__, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price__, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genere__, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(addBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeBookBtn)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	//event when the window is opened
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
	//Adding some example data (as default data) for tests
        clientDatabase.add(new ClientInfo(1, "The Story of us", "Ayush", "10/1/2023", "2/2/2023", "8567492746", "ayushg@gmail.com"));
        clientDatabase.add(new ClientInfo(2, "The Story of us 2", "Ayush 2", "11/1/2023", "3/2/2023", "8567492748", "ayush2g@gmail.com"));
        clientDatabase.add(new ClientInfo(3, "The Story of us 3", "Ayush 3", "12/1/2023", "4/2/2023", "8567492749", "ayush3g@gmail.com"));
        clientDatabase.add(new ClientInfo(4, "The Story of us 4", "Ayush 4", "13/1/2023", "5/2/2023", "8567492740", "ayush4g@gmail.com"));
        
        bookDatabase.add(new BookInfo(1, "The Story of us", 200, "Drama"));
        bookDatabase.add(new BookInfo(2, "The Story of us 2", 300, "Drama"));
        bookDatabase.add(new BookInfo(3, "The Story of us 3", 400, "Drama"));
        bookDatabase.add(new BookInfo(4, "The Story of us 4", 500, "Drama"));
        
	//Calling the custom method to load the data from our database variable (PatientInfo List) to UI JList
        LoadDatabaseToUI();
		
    }//GEN-LAST:event_formWindowOpened

	//Event when user pressed the Update button
    private void returnBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookBtnActionPerformed
        // TODO add your handling code here:
        
	//a Try-Cache to avoid throwing exceptions for anything
        try
        {
			
            clientDatabase.remove(readersList.getSelectedIndex());
        
            LoadDatabaseToUI();
        }
        catch(Exception ec)
        {
        
        }
        
    }//GEN-LAST:event_returnBookBtnActionPerformed

    private void issueBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBookBtnActionPerformed
        // TODO add your handling code here:
        try
        {
            ClientInfo p = new ClientInfo(Integer.parseInt(__ID.getText()), __name.getText(), __readerName.getText(), __issueDate.getText(), __dueDate.getText(), __phoneNumber.getText(), __email.getText());
        
            clientDatabase.add(p);
            
            __ID.setText("");
            __name.setText("");
            __readerName.setText("");
            __issueDate.setText("");
            __dueDate.setText("");
            __phoneNumber.setText("");
            __email.setText("");
            
            LoadDatabaseToUI();
        }
        catch(Exception ec)
        {
        
        }
    }//GEN-LAST:event_issueBookBtnActionPerformed

    private void removeBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBookBtnActionPerformed
        // TODO add your handling code here:
        //a Try-Cache to avoid throwing exceptions for anything
        try
        {
			
            bookDatabase.remove(booksList.getSelectedIndex());
        
            LoadDatabaseToUI();
        }
        catch(Exception ec)
        {
        
        }
    }//GEN-LAST:event_removeBookBtnActionPerformed

    private void addBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookBtnActionPerformed
        // TODO add your handling code here:
        try
        {
            BookInfo p = new BookInfo(Integer.parseInt(id__.getText()), name__.getText(), Integer.parseInt(price__.getText()), genere__.getText());
        
            bookDatabase.add(p);
            
            id__.setText("");
            name__.setText("");
            price__.setText("");
            genere__.setText("");
            
            LoadDatabaseToUI();
        }
        catch(Exception ec)
        {
        
        }
    }//GEN-LAST:event_addBookBtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels=javax.swing.UIManager.getInstalledLookAndFeels();
            for (int idx=0; idx<installedLookAndFeels.length; idx++)
                if ("Nimbus".equals(installedLookAndFeels[idx].getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeels[idx].getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
        
    }
    
	//Our custom method to load all data from the database (PatientInfo list) to UI JList
    public void LoadDatabaseToUI()
    {
	//clearning the JList
        readersList.removeAll();
        booksList.removeAll();
		
	//Declaring a new List Model to set in JList
        DefaultListModel values1 = new DefaultListModel();
        DefaultListModel values2 = new DefaultListModel();
		
	//Iterating through all elements of the database
        for(int i=0; i<clientDatabase.size(); i++)
        {
            //Adding the names each Patient name from the currrent database
            values1.addElement(clientDatabase.get(i).ReaderName);
        }
        for(int i=0; i<bookDatabase.size(); i++)
        {
            //Adding the names each Patient name from the currrent database
            values2.addElement(bookDatabase.get(i).BookName);
        }
		
	//Setting our declared model to the JList to show in UI
        readersList.setModel(values1);
        booksList.setModel(values2);
    }
    
    //Our custom class to store managed data into
    public class ClientInfo {
        public int ID;
        public String BookName;
        public String ReaderName;
        public String IssueDate;
        public String DueDate;
        public String PhoneNumber;
        public String Email;
        
        ClientInfo(int _bookid, String _bookname, String _readername, String _issuedate, String _duedate, String _phoneNumber, 
		String _email)
        {
            ID = _bookid;
            BookName = _bookname;
            ReaderName = _readername;
            IssueDate = _issuedate;
            DueDate = _duedate;
            PhoneNumber = _phoneNumber;
            Email = _email;
        }
    }
    
    public class BookInfo {
        public int ID;
        public String BookName;
        public int Price;
        public String Genere;
        
        BookInfo(int _bookid, String _bookname, int _price, String _genere)
        {
            ID = _bookid;
            BookName = _bookname;
            Price = _price;
            Genere = _genere;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField __ID;
    private javax.swing.JTextField __dueDate;
    private javax.swing.JTextField __email;
    private javax.swing.JTextField __issueDate;
    private javax.swing.JTextField __name;
    private javax.swing.JTextField __phoneNumber;
    private javax.swing.JTextField __readerName;
    private javax.swing.JButton addBookBtn;
    private javax.swing.JList<String> booksList;
    private javax.swing.JTextField genere__;
    private javax.swing.JTextField id__;
    private javax.swing.JButton issueBookBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField name__;
    private javax.swing.JTextField price__;
    private javax.swing.JList<String> readersList;
    private javax.swing.JButton removeBookBtn;
    private javax.swing.JButton returnBookBtn;
    // End of variables declaration//GEN-END:variables
    
}